[package]
name = "ontubevis-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
cfg-if = "1"
anyhow = "1.0.89"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
winit = {version="0.30.5", features=["rwh_05"]}
wgpu = "22.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wgpu = {version="22.1", features=["webgl"]}
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = { version="0.3.70", features=["Document", "Element", "Window"]}

[lib]
crate-type = ["cdylib", "rlib"]
