[package]
name = "ontubevis-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
cfg-if = "1"
anyhow = "1.0.89"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
wgpu = {git="https://github.com/gfx-rs/wgpu.git", branch="trunk"}
nalgebra-glm = "0.19"
image = {version="0.25.2", default-features=false, features=["png", "jpeg"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"
winit = {version="0.30.5", default-features=false, features=["x11", "rwh_06"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wgpu = {git="https://github.com/gfx-rs/wgpu.git", branch="trunk", features=["webgpu"]}
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = {version="0.3.70", features=["Document", "Element", "Window", "DomQuad", "DomRect"]}
winit = {version="0.30.5"}

[lib]
crate-type = ["cdylib", "rlib"]
